Repository cutenode/good-first-issue, pull requests merged in 2018-12, with the labels that each got.

#70 Added Apollo org
  README.md
  data/projects.json
Labels: release queue

#66 Add React & React Native
  README.md
  data/projects.json
Labels: ready to release, release queue

#67 Added babel
  README.md
  data/projects.json
Labels: release queue

#82 add mochajs/mocha
  README.md
  data/projects.json
Labels: release queue

#93 added download badge
  README.md
Labels: enhancement

#71 Added React Navigation
  README.md
  data/projects.json
Labels: projects, release queue
